In [ ]:
import torch
import torch.nn as nn
from torch.nn import CrossEntropyLoss
import numpy as np
out = torch.Tensor(np.array([[
    [
        [1.,1, 1], 
        [0, 0, 0], 
        [0, 0, 0],
        [0, 0, 0]
    ],
    [
        [0, 0, 0],
        [1, 1, 1],
        [0, 0.,0],
        [0, 0, 0]
    ],
    [
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]
    ],
    [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1]
    ]
]]))

target = torch.Tensor([[
    [0, 0, 0],
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
]]).type('torch.LongTensor')
criterion = CrossEntropyLoss()


In [ ]:
# print(out.shape)
# print(target.shape)
# print(criterion(out, target))
# values, indices = torch.max(out, dim=1)
# print(values, indices)
# print(indices.shape)

# print(target)
# print(target==3)
# print(np.sum(target.numpy()==3))

a = torch.zeros((2, 5, 5), dtype=torch.float)
print(a)
print(a.shape)
a[0] = 5
print(a)


In [ ]:
sm = nn.Softmax(dim=1)
print(sm(out))

In [ ]:
print(torch.log(sm(out)))

In [ ]:
loss = nn.NLLLoss()
print(loss(torch.log(sm(out)), target))

In [ ]:
print(np.zeros(4))

In [53]:
import torch
import torch.nn as nn

m = nn.Dropout(p=0.3)
input = torch.ones( 5, 5)
print(input)


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [54]:
print(input.mean())

tensor(1.)


In [55]:
output = m(input)
print(output)

tensor([[1.4286, 1.4286, 1.4286, 1.4286, 1.4286],
        [0.0000, 0.0000, 1.4286, 0.0000, 1.4286],
        [0.0000, 0.0000, 1.4286, 0.0000, 1.4286],
        [1.4286, 0.0000, 0.0000, 1.4286, 1.4286],
        [1.4286, 1.4286, 1.4286, 0.0000, 1.4286]])


In [56]:
print(input/0.7)

tensor([[1.4286, 1.4286, 1.4286, 1.4286, 1.4286],
        [1.4286, 1.4286, 1.4286, 1.4286, 1.4286],
        [1.4286, 1.4286, 1.4286, 1.4286, 1.4286],
        [1.4286, 1.4286, 1.4286, 1.4286, 1.4286],
        [1.4286, 1.4286, 1.4286, 1.4286, 1.4286]])


In [61]:
print((output*.7).mean())

tensor(0.6400)
