In [15]:
import torch
import torch.nn as nn
from torch.nn import CrossEntropyLoss
import numpy as np
out = torch.Tensor(np.array([[
    [
        [1.,1, 1], 
        [0, 0, 0], 
        [0, 0, 0],
        [0, 0, 0]
    ],
    [
        [0, 0, 0],
        [1, 1, 1],
        [0, 0.,0],
        [0, 0, 0]
    ],
    [
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]
    ],
    [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 1, 1]
    ]
]]))

target = torch.Tensor([[
    [0, 0, 0],
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
]]).type('torch.LongTensor')
criterion = CrossEntropyLoss()


In [21]:
print(out.shape)
print(target.shape)
print(criterion(out, target))
values, indices = torch.max(out, dim=1)
print(values, indices)
print(indices.shape)


torch.Size([1, 4, 4, 3])
torch.Size([1, 4, 3])
tensor(0.7437)
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) tensor([[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])
torch.Size([1, 4, 3])


In [4]:
sm = nn.Softmax(dim=1)
print(sm(out))

tensor([[[[0.4754, 0.4754, 0.4754],
          [0.1749, 0.1749, 0.1749],
          [0.1749, 0.1749, 0.1749],
          [0.1749, 0.1749, 0.1749]],

         [[0.1749, 0.1749, 0.1749],
          [0.4754, 0.4754, 0.4754],
          [0.1749, 0.1749, 0.1749],
          [0.1749, 0.1749, 0.1749]],

         [[0.1749, 0.1749, 0.1749],
          [0.1749, 0.1749, 0.1749],
          [0.4754, 0.4754, 0.4754],
          [0.1749, 0.1749, 0.1749]],

         [[0.1749, 0.1749, 0.1749],
          [0.1749, 0.1749, 0.1749],
          [0.1749, 0.1749, 0.1749],
          [0.4754, 0.4754, 0.4754]]]])


In [5]:
print(torch.log(sm(out)))

tensor([[[[-0.7437, -0.7437, -0.7437],
          [-1.7437, -1.7437, -1.7437],
          [-1.7437, -1.7437, -1.7437],
          [-1.7437, -1.7437, -1.7437]],

         [[-1.7437, -1.7437, -1.7437],
          [-0.7437, -0.7437, -0.7437],
          [-1.7437, -1.7437, -1.7437],
          [-1.7437, -1.7437, -1.7437]],

         [[-1.7437, -1.7437, -1.7437],
          [-1.7437, -1.7437, -1.7437],
          [-0.7437, -0.7437, -0.7437],
          [-1.7437, -1.7437, -1.7437]],

         [[-1.7437, -1.7437, -1.7437],
          [-1.7437, -1.7437, -1.7437],
          [-1.7437, -1.7437, -1.7437],
          [-0.7437, -0.7437, -0.7437]]]])


In [6]:
loss = nn.NLLLoss()
print(loss(torch.log(sm(out)), target))

tensor(0.7437)


In [26]:
print(np.zeros(4))

[0. 0. 0. 0.]
